services:

  mariadb:
    image: mariadb:11.4.5
    container_name: ${PROJECT_NAME}-db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    restart: always
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - ./mariadb-init:/docker-entrypoint-initdb.d
      # - ./database:/var/lib/mysql
#     networks:
#       - simone

# networks:
#   simone:
#     name: simone
