services:

  mariadb:
    image: mariadb:11.4.5
    container_name: ${PROJECT_NAME}-db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    restart: always
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - ./mariadb-init:/docker-entrypoint-initdb.d

#   mistral:
#     image: ollama/ollama
#     container_name: mistral
#     restart: always
#     ports:
#       - 11434:11434
#     volumes:
#       - ollama_data:/root/.ollama
#     command: >
#       bash -c "
#         ollama serve &
#         sleep 5 &&
#         ollama pull mistral:7B-F16
#         wait
#       "

# volumes:
#   ollama_data:


# networks:
#   simone:
#     name: simone
